services:
  nginx:
    #image: nginx:latest
    container_name: nginx
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./CI4:/var/www
    depends_on:
      - php_fpm
      - mysql
    ports:
      - "8000:80"

  php_fpm:
    container_name: php_fpm
    build: ./docker/php
    volumes:
      - ./CI4:/var/www

  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    depends_on:
      - mysql
    ports:
      - 1500:80
    environment:
      - PMA_HOST=mysql

#  postgresql:
#    container_name: postgresql
#    image: postgres:15
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=password
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
#    ports:
#      - 5432:5432
#
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: 'teste@teste.com'
#      PGADMIN_DEFAULT_PASSWORD: 'teste'
#    volumes:
#      - ./docker/pgadmin4/servers.json:/pgadmin4/servers.json
#    ports:
#      - 5555:80
