services:
  nginx:
    container_name: nginx
    image: dockerhub.timeweb.cloud/library/nginx:latest
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./CI4:/var/www
    depends_on:
      - php_fpm
      - mysql
    ports:
      - "8000:80"

  php_fpm:
    container_name: php_fpm
    build: ./docker/php
    volumes:
      - ./CI4:/var/www
    #command: /bin/sh -c "mkdir 11111"
    #command: sh -cx 'php /var/www/composer.phar install -d /var/www'

  mysql:
    container_name: mysql
    image: dockerhub.timeweb.cloud/library/mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    container_name: phpmyadmin
    image: dockerhub.timeweb.cloud/library/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 1500:80
    environment:
      - PMA_HOST=mysql